export const genresList = [
    'Pop',
    'House',
    'Lo-Fi',
    'Rock',
    'Ambient',
    'Hip-Hop/Rap',
    'Jazz',
    'Trap',
    'Metal',
    'Electronic',
    'Techno',
    'Trap',
    'Classical',
    'Dubstep',
    'R&B/Soul',
]